### Libraries

In [52]:
import pandas as pd
from pandas import json_normalize

import requests 
import json
import os
from dotenv import load_dotenv 

import time

import re

from bs4 import BeautifulSoup as bs
from fuzzywuzzy import fuzz

C:\Users\danid\miniconda3\envs\ironhack\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

### Setting api key

In [7]:
load_dotenv()

True

In [8]:
key = os.getenv("api-key")

In [9]:
url = f'https://imdb-api.com/API/MostPopularMovies/{key}'

In [10]:
res = requests.get(url)

In [11]:
res

In [12]:
res.json()

{'items': [{'id': 'tt1630029',
   'rank': '1',
   'rankUpDown': '+1',
   'title': 'Avatar: The Way of Water',
   'fullTitle': 'Avatar: The Way of Water (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_UX128_CR0,1,128,176_AL_.jpg',
   'crew': 'James Cameron (dir.), Sam Worthington, Zoe Saldana',
   'imDbRating': '7.8',
   'imDbRatingCount': '279734'},
  {'id': 'tt9764362',
   'rank': '2',
   'rankUpDown': '-1',
   'title': 'The Menu',
   'fullTitle': 'The Menu (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BMzdjNjI5MmYtODhiNS00NTcyLWEzZmUtYzVmODM5YzExNDE3XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Mark Mylod (dir.), Ralph Fiennes, Anya Taylor-Joy',
   'imDbRating': '7.2',
   'imDbRatingCount': '210081'},
  {'id': 'tt10640346',
   'rank': '3',
   'rankUpDown': '+1',
   'title': 'Babylon',
   'fullTitle': 'Babylon (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNjlkYjc4NGMtZjc3MS00NjQ3LTk4MmUtMTkwZGZjODE1ZDVlXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Damien Chazelle (dir.), Brad Pitt, Margot Robbie',
   'imDbRating': '7.5',
   'imDbRatingCount': '46092'},
  {'id': 'tt6710474',
   'rank': '4',
   'rankUpDown': '+5',
   'title': 'Everything Everywhere All at Once',
   'fullTitle': 'Everything Everywhere All at Once (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu',
   'imDbRating': '8.0',
   'imDbRatingCount': '314824'},
  {'id': 'tt8760708',
   'rank': '5',
   'rankUpDown': '0',
   'title': 'M3GAN',
   'fullTitle': 'M3GAN (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BMDk4MTdhYzEtODk3OS00ZDBjLWFhNTQtMDI2ODdjNzQzZTA3XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Gerard Johnstone (dir.), Allison Williams, Violet McGraw',
   'imDbRating': '6.4',
   'imDbRatingCount': '51486'},
  {'id': 'tt11813216',
   'rank': '6',
   'rankUpDown': '+2',
   'title': 'The Banshees of Inisherin',
   'fullTitle': 'The Banshees of Inisherin (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BM2NlZDI0ZDktNTg5OS00ZjQ1LWI4MDEtN2I0MDE5NWRiNzA4XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Martin McDonagh (dir.), Colin Farrell, Brendan Gleeson',
   'imDbRating': '7.8',
   'imDbRatingCount': '117266'},
  {'id': 'tt12844910',
   'rank': '7',
   'rankUpDown': '+291',
   'title': 'Pathaan',
   'fullTitle': 'Pathaan (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BM2QzM2JiNTMtYjU4Ny00MDZkLTk3MmUtYTRjMzVkZGJlNmYyXkEyXkFqcGdeQXVyMTUzNTgzNzM0._V1_UY176_CR0,0,128,176_AL_.jpg',
   'crew': 'Siddharth Anand (dir.), Shah Rukh Khan, Deepika Padukone',
   'imDbRating': '6.7',
   'imDbRatingCount': '110749'},
  {'id': 'tt14826022',
   'rank': '8',
   'rankUpDown': '+84',
   'title': 'You People',
   'fullTitle': 'You People (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BZDU3YmRmYTQtNDFjNy00MDc1LWJiYzEtNDc0MDg0YTIwYzYxXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Kenya Barris (dir.), Jonah Hill, Lauren London',
   'imDbRating': '5.6',
   'imDbRatingCount': '27988'},
  {'id': 'tt15486810',
   'rank': '9',
   'rankUpDown': '0',
   'title': 'Teen Wolf: The Movie',
   'fullTitle': 'Teen Wolf: The Movie (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BYWYyZWU5NzctYjY4Zi00MzYyLTgxZTMtZjBmYWE2NGMwYTllXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Russell Mulcahy (dir.), Tyler Posey, Crystal Reed',
   'imDbRating': '5.8',
   'imDbRatingCount': '7201'},
  {'id': 'tt3915174',
   'rank': '10',
   'rankUpDown': '-4',
   'title': 'Puss in Boots: The Last Wish',
   'fullTitle': 'Puss in Boots: The Last Wish (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNjMyMDBjMGUtNDUzZi00N2MwLTg1MjItZTk2MDE1OTZmNTYxXkEyXkFqcGdeQXVyMTQ5NjA0NDM0._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Joel Crawford (dir.), Antonio Banderas, Salma Hayek',
   'imDbRating': '7.9',
   'imDbRatingCount': '61759'},
  {'id': 'tt14138650',
   'rank': '11',
   'rankUpDown': '-8',
   'title': 'The Pale Blue Eye',
   'fullTitle': 'The Pale Blue Eye (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BZDg2YThlMTItYzhhMy00OWE3LTljYTAtYTExMDM5NzRjOGFhXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Scott Cooper (dir.), Christian Bale, Harry Melling',
   'imDbRating': '6.6',
   'imDbRatingCount': '78321'},
  {'id': 'tt10365998',
   'rank': '12',
   'rankUpDown': '+99',
   'title': 'Infinity Pool',
   'fullTitle': 'Infinity Pool (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BZDQxZTY0ZDItY2Y0Yy00OTIzLTkwYTgtNmNkODhiYTk4MzUwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Brandon Cronenberg (dir.), Alexander Skarsgård, Mia Goth',
   'imDbRating': '6.8',
   'imDbRatingCount': '3214'},
  {'id': 'tt7322224',
   'rank': '13',
   'rankUpDown': '+8',
   'title': 'Triangle of Sadness',
   'fullTitle': 'Triangle of Sadness (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNDRiZjc0ZDMtMjhlYi00ZjAzLTg0MDQtZDI2NGEyYTBlN2M2XkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Ruben Östlund (dir.), Thobias Thorwid, Harris Dickinson',
   'imDbRating': '7.5',
   'imDbRatingCount': '74238'},
  {'id': 'tt11564570',
   'rank': '14',
   'rankUpDown': '-7',
   'title': 'Glass Onion',
   'fullTitle': 'Glass Onion (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BYmZlZDZkZjYtNzE5Mi00ODFhLTk2OTgtZWVmODBiZTI4NGFiXkEyXkFqcGdeQXVyMTE5MTg5NDIw._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Rian Johnson (dir.), Daniel Craig, Edward Norton',
   'imDbRating': '7.2',
   'imDbRatingCount': '317912'},
  {'id': 'tt13833688',
   'rank': '15',
   'rankUpDown': '-4',
   'title': 'The Whale',
   'fullTitle': 'The Whale (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BZDQ4Njg4YTctNGZkYi00NWU1LWI4OTYtNmNjOWMyMjI1NWYzXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX128_CR0,1,128,176_AL_.jpg',
   'crew': 'Darren Aronofsky (dir.), Brendan Fraser, Sadie Sink',
   'imDbRating': '8.0',
   'imDbRatingCount': '21899'},
  {'id': 'tt14208870',
   'rank': '16',
   'rankUpDown': '-4',
   'title': 'The Fabelmans',
   'fullTitle': 'The Fabelmans (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BZGM1MzczNmQtMjBmYS00NTRhLWI0MzctNTFkZDc4OGUyODdjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Steven Spielberg (dir.), Michelle Williams, Gabriel LaBelle',
   'imDbRating': '7.7',
   'imDbRatingCount': '47116'},
  {'id': 'tt14444726',
   'rank': '17',
   'rankUpDown': '-2',
   'title': 'Tár',
   'fullTitle': 'Tár (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BM2I0ZDcyYzItMGEyNi00YWVhLTlmNTQtOWVlYjE1ZGVhNWM0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Todd Field (dir.), Cate Blanchett, Noémie Merlant',
   'imDbRating': '7.6',
   'imDbRatingCount': '32037'},
  {'id': 'tt9686790',
   'rank': '18',
   'rankUpDown': '+33',
   'title': 'Shotgun Wedding',
   'fullTitle': 'Shotgun Wedding (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BN2IwZDU2NDAtNmJlYS00NDJlLWI1ZjQtOTViY2I0YWZlM2U1XkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Jason Moore (dir.), Jennifer Lopez, Josh Duhamel',
   'imDbRating': '5.5',
   'imDbRatingCount': '14120'},
  {'id': 'tt1016150',
   'rank': '19',
   'rankUpDown': '+18',
   'title': 'All Quiet on the Western Front',
   'fullTitle': 'All Quiet on the Western Front (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BYTE1MmZiMWYtYTFmZi00YjA3LWI2ODgtMWFlNWYxZjdmNGE3XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Edward Berger (dir.), Felix Kammerer, Albrecht Schuch',
   'imDbRating': '7.8',
   'imDbRatingCount': '128051'},
  {'id': 'tt7405458',
   'rank': '20',
   'rankUpDown': '-10',
   'title': 'A Man Called Otto',
   'fullTitle': 'A Man Called Otto (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNzg3OTEzMTgtYWU0OC00YTI0LWIxOTAtNmRkNTc0Nzg2YWU1XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Marc Forster (dir.), Tom Hanks, Mariana Treviño',
   'imDbRating': '7.6',
   'imDbRatingCount': '13409'},
  {'id': 'tt19770238',
   'rank': '21',
   'rankUpDown': '+8',
   'title': 'Aftersun',
   'fullTitle': 'Aftersun (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BMTM3OTU0ZGUtNzYwYy00ODU3LWI3YjgtOWZlODliMmRiMWEzXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Charlotte Wells (dir.), Paul Mescal, Frankie Corio',
   'imDbRating': '7.8',
   'imDbRatingCount': '31208'},
  {'id': 'tt2906216',
   'rank': '22',
   'rankUpDown': '+290',
   'title': 'Dungeons & Dragons: Honor Among Thieves',
   'fullTitle': 'Dungeons & Dragons: Honor Among Thieves (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BZjAyMGMwYTEtNDk4ZS00YmY0LThhZjUtOWI4ZjFmZmU4N2I3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'John Francis Daley (dir.), Chris Pine, Michelle Rodriguez',
   'imDbRating': '',
   'imDbRatingCount': '0'},
  {'id': 'tt1745960',
   'rank': '23',
   'rankUpDown': '-3',
   'title': 'Top Gun: Maverick',
   'fullTitle': 'Top Gun: Maverick (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly',
   'imDbRating': '8.3',
   'imDbRatingCount': '515609'},
  {'id': 'tt9737876',
   'rank': '24',
   'rankUpDown': '+2432',
   'title': "Narvik: Hitler's First Defeat",
   'fullTitle': "Narvik: Hitler's First Defeat (2022)",
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNmVlY2Q1OTUtZjRmYi00OTZiLTg5NzktM2M0ZGViNzczOThlXkEyXkFqcGdeQXVyMDMxMTgwOQ@@._V1_UX128_CR0,1,128,176_AL_.jpg',
   'crew': 'Erik Skjoldbjærg (dir.), Kristine Hartgen, Billy Campbell',
   'imDbRating': '6.6',
   'imDbRatingCount': '6890'},
  {'id': 'tt13669038',
   'rank': '25',
   'rankUpDown': '+25',
   'title': 'Women Talking',
   'fullTitle': 'Women Talking (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BYTZmMmQ4OWYtM2JmNC00NzY0LWJhODUtOTRmMWMyOTU4OWQ4XkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Sarah Polley (dir.), Rooney Mara, Claire Foy',
   'imDbRating': '7.5',
   'imDbRatingCount': '3783'},
  {'id': 'tt13560574',
   'rank': '26',
   'rankUpDown': '-12',
   'title': 'X',
   'fullTitle': 'X (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BMTJiMmE5YWItOWZjYS00YTg0LWE0MTYtMzg2ZTY4YjNkNDEzXkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Ti West (dir.), Mia Goth, Jenna Ortega',
   'imDbRating': '6.6',
   'imDbRatingCount': '110896'},
  {'id': 'tt22352848',
   'rank': '27',
   'rankUpDown': '+146',
   'title': 'Jung_E',
   'fullTitle': 'Jung_E (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BODQzZmE5NWUtODIyMi00MWVlLWJmMTYtNjAyN2ZjNGQ0ZmNkXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Sang-ho Yeon (dir.), Lee Dong-Hee, Lee Ga-Kyung',
   'imDbRating': '5.4',
   'imDbRatingCount': '6486'},
  {'id': 'tt5884796',
   'rank': '28',
   'rankUpDown': '-15',
   'title': 'Plane',
   'fullTitle': 'Plane (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BZDc4MzVkNzYtZTRiZC00ODYwLWJjZmMtMDIyNjQ1M2M1OGM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Jean-François Richet (dir.), Gerard Butler, Daniella Pineda',
   'imDbRating': '6.7',
   'imDbRatingCount': '11458'},
  {'id': 'tt13131232',
   'rank': '29',
   'rankUpDown': '+28',
   'title': 'Mission Majnu',
   'fullTitle': 'Mission Majnu (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BYTYwYmI0NGItYmFkYi00NzViLWIwMGEtNGNjYjQwYjY1NTQ1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Shantanu Bagchi (dir.), Sidharth Malhotra, Rashmika Mandanna',
   'imDbRating': '7.8',
   'imDbRatingCount': '37081'},
  {'id': 'tt12593682',
   'rank': '30',
   'rankUpDown': '-14',
   'title': 'Bullet Train',
   'fullTitle': 'Bullet Train (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BOTBhZGJjYjQtODRjOC00MWJhLTk1NTctZDJiM2JkMTY3MGNiXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'David Leitch (dir.), Brad Pitt, Joey King',
   'imDbRating': '7.3',
   'imDbRatingCount': '282806'},
  {'id': 'tt3704428',
   'rank': '31',
   'rankUpDown': '-7',
   'title': 'Elvis',
   'fullTitle': 'Elvis (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BYzMzNTJjYmMtZTkxNS00MjI4LWI3YmQtOTQ4MDZjZDJlZjQyXkEyXkFqcGdeQXVyNjc0NzQzNTM@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Baz Luhrmann (dir.), Tom Hanks, Austin Butler',
   'imDbRating': '7.4',
   'imDbRatingCount': '173914'},
  {'id': 'tt8946378',
   'rank': '32',
   'rankUpDown': '-15',
   'title': 'Knives Out',
   'fullTitle': 'Knives Out (2019)',
   'year': '2019',
   'image': 'https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Rian Johnson (dir.), Daniel Craig, Chris Evans',
   'imDbRating': '7.9',
   'imDbRatingCount': '699464'},
  {'id': 'tt17663992',
   'rank': '33',
   'rankUpDown': '-15',
   'title': 'Scream VI',
   'fullTitle': 'Scream VI (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BYTQ5OTkxNGEtZjZkMS00ZjBlLWE2OWYtM2ZkOTU3MjRlNzAxXkEyXkFqcGdeQXVyMTQzNTA5MzYz._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'Matt Bettinelli-Olpin (dir.), Melissa Barrera, Courteney Cox',
   'imDbRating': '',
   'imDbRatingCount': '0'},
  {'id': 'tt0499549',
   'rank': '34',
   'rankUpDown': '-15',
   'title': 'Avatar',
   'fullTitle': 'Avatar (2009)',
   'year': '2009',
   'image': 'https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'James Cameron (dir.), Sam Worthington, Zoe Saldana',
   'imDbRating': '7.9',
   'imDbRatingCount': '1317257'},
  {'id': 'tt10954600',
   'rank': '35',
   'rankUpDown': '-13',
   'title': 'Ant-Man and the Wasp: Quantumania',
   'fullTitle': 'Ant-Man and the Wasp: Quantumania (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BMDIzM2FlNTctNjAzZi00YzhkLThjYWQtMDY5Njc0NjdmMGVlXkEyXkFqcGdeQXVyMTUzOTcyODA5._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Peyton Reed (dir.), Paul Rudd, Evangeline Lilly',
   'imDbRating': '',
   'imDbRatingCount': '0'},
  {'id': 'tt15679400',
   'rank': '36',
   'rankUpDown': '+17',
   'title': 'Knock at the Cabin',
   'fullTitle': 'Knock at the Cabin (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BZTc4MjU0MjMtYTEwNy00YjNlLTk2MGYtMjNlNzFjMmY4MjQ0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'M. Night Shyamalan (dir.), Dave Bautista, Jonathan Groff',
   'imDbRating': '6.4',
   'imDbRatingCount': '5383'},
  {'id': 'tt7693316',
   'rank': '37',
   'rankUpDown': '-4',
   'title': 'Devotion',
   'fullTitle': 'Devotion (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BMjI5NGJjMmEtODk4Yy00ZDRjLWE5ZGItMjJiNGM4NTI0NmZkXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'J.D. Dillard (dir.), Jonathan Majors, Glen Powell',
   'imDbRating': '6.7',
   'imDbRatingCount': '13388'},
  {'id': 'tt8129806',
   'rank': '38',
   'rankUpDown': '+55',
   'title': 'To Leslie',
   'fullTitle': 'To Leslie (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNmNiMGRkYmUtYjI4MC00ZDg4LTk3YjktNTczNzEzYmExMjAwXkEyXkFqcGdeQXVyMTQ4MTk0NjYx._V1_UX128_CR0,1,128,176_AL_.jpg',
   'crew': 'Michael Morris (dir.), Andrea Riseborough, Allison Janney',
   'imDbRating': '7.1',
   'imDbRatingCount': '3683'},
  {'id': 'tt13539646',
   'rank': '39',
   'rankUpDown': '+3111',
   'title': 'The Wandering Earth II',
   'fullTitle': 'The Wandering Earth II (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BN2IzY2E2MTQtNTMxMy00YTJjLTkzYTEtYzAyM2VlYjFjZDQzXkEyXkFqcGdeQXVyMTI5ODA1OTU0._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Frant Gwo (dir.), Andy Lau, Jing Wu',
   'imDbRating': '8.0',
   'imDbRatingCount': '5732'},
  {'id': 'tt14308636',
   'rank': '40',
   'rankUpDown': '-6',
   'title': 'Bank of Dave',
   'fullTitle': 'Bank of Dave (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BYWEyOGM0MTAtNGUzYy00YWQ4LWE4ODAtNzY5MWRjOTY3MjEzXkEyXkFqcGdeQXVyMzI2NTcxODU@._V1_UX128_CR0,1,128,176_AL_.jpg',
   'crew': 'Chris Foggin (dir.), Phoebe Dynevor, Joel Fry',
   'imDbRating': '7.2',
   'imDbRatingCount': '3820'},
  {'id': 'tt11976532',
   'rank': '41',
   'rankUpDown': '+39',
   'title': 'Vengeance',
   'fullTitle': 'Vengeance (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNDkyZGFjZDEtODdiZS00YmJiLWE2NTEtZGIxMTUzN2ZjZjA3XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'B.J. Novak (dir.), B.J. Novak, Boyd Holbrook',
   'imDbRating': '6.8',
   'imDbRatingCount': '21747'},
  {'id': 'tt0092099',
   'rank': '42',
   'rankUpDown': '+1',
   'title': 'Top Gun',
   'fullTitle': 'Top Gun (1986)',
   'year': '1986',
   'image': 'https://m.media-amazon.com/images/M/MV5BZjQxYTA3ODItNzgxMy00N2Y2LWJlZGMtMTRlM2JkZjI1ZDhhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Tony Scott (dir.), Tom Cruise, Tim Robbins',
   'imDbRating': '6.9',
   'imDbRatingCount': '458935'},
  {'id': 'tt18079362',
   'rank': '43',
   'rankUpDown': '-13',
   'title': '80 for Brady',
   'fullTitle': '80 for Brady (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BNzY4MzQ1MTgtNGZiYS00Y2M5LWJmODUtYzIzNWFlOGZjMjk5XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'Kyle Marvin (dir.), Rita Moreno, Sally Field',
   'imDbRating': '5.5',
   'imDbRatingCount': '564'},
  {'id': 'tt10151854',
   'rank': '44',
   'rankUpDown': '+541',
   'title': 'Shazam! Fury of the Gods',
   'fullTitle': 'Shazam! Fury of the Gods (2023)',
   'year': '2023',
   'image': 'https://m.media-amazon.com/images/M/MV5BZTJkMTBjZWEtMzhhMy00MjlkLTkyNTYtNGZjNGM4Mjk5YTEyXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UY176_CR6,0,128,176_AL_.jpg',
   'crew': 'David F. Sandberg (dir.), Zachary Levi, Grace Caroline Currey',
   'imDbRating': '',
   'imDbRatingCount': '0'},
  {'id': 'tt10304142',
   'rank': '45',
   'rankUpDown': '-17',
   'title': 'Amsterdam',
   'fullTitle': 'Amsterdam (2022)',
   'year': '2022',
   'image': 'https://m.media-amazon.com/images/M/MV5BNDQwNzE0ZTItYmZjMC00NjI3LWFlNzctNTExZDY2NWE0Zjc0XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX128_CR0,3,128,176_AL_.jpg',
   'crew': 'David O. Russell (dir.), Christian Bale, Margot Robbie',
   'imDbRating': '6.1',
   'imDbRatingCount': '62510'},
  {'id': 'tt10855768',
   'rank': '46',
   'rankUpDown': '+13',
   'title': 'Missing',
   'fullTitle': 'Missing (2023)',
   'year': '2023',

### Web Scrapping - IMDB Netflix List

In [13]:
url_imdb = 'https://www.imdb.com/search/title/?companies=co0144901'
headers = {'Accept-Language': 'en-US,en;q=0.5'}
html = requests.get(url_imdb, headers=headers)

In [14]:
soup = bs(html.content, 'html.parser')

In [15]:
titles = soup.find_all("div", attrs = {"class":"psf-widget"})

In [16]:
title = soup.select("div h3 a")
title_ = [i.getText().strip() for i in title]
title_

["That '90s Show",
 'Wednesday',
 'You People',
 'Ginny & Georgia',
 'The Walking Dead',
 'The Pale Blue Eye',
 "That '70s Show",
 'Glass Onion',
 'All Quiet on the Western Front',
 'Fauda',
 'Breaking Bad',
 'Vikings: Valhalla',
 'Happy Valley',
 'Kaleidoscope',
 "Narvik: Hitler's First Defeat",
 'Women at War',
 'Jung_E',
 'Cobra Kai',
 'Better Call Saul',
 'Rick and Morty',
 'Mission Majnu',
 'Bullet Train',
 'Stranger Things',
 'Shahmaran',
 "Grey's Anatomy",
 'New Amsterdam',
 'Vikings',
 'Supernatural',
 'NCIS',
 'The Crown',
 'Devotion',
 'Peaky Blinders',
 'Bank of Dave',
 'Alice in Borderland',
 'Top Gun',
 'Friends',
 'Lockwood & Co',
 'RRR',
 'Teen Wolf',
 'Modern Family',
 'The Recruit',
 'Blonde',
 "Guillermo del Toro's Pinocchio",
 'You',
 'The Blacklist',
 'American Horror Story',
 'Attack on Titan',
 'Suits',
 'The Last Kingdom',
 'Shameless']

In [17]:
title[0].get('href')

'/title/tt15591076/'

In [18]:
genre = soup.select("span.genre")
genre_ = [i.getText().strip() for i in genre]
genre_

['Comedy, Drama, Romance',
 'Comedy, Crime, Fantasy',
 'Comedy, Romance',
 'Comedy, Drama',
 'Drama, Horror, Thriller',
 'Crime, Horror, Mystery',
 'Comedy, Drama, Romance',
 'Comedy, Crime, Drama',
 'Action, Drama, War',
 'Action, Drama, Thriller',
 'Crime, Drama, Thriller',
 'Action, Adventure, Drama',
 'Crime, Drama, Thriller',
 'Action, Crime, Drama',
 'Drama, History, War',
 'Drama, History',
 'Action, Adventure, Drama',
 'Action, Comedy, Drama',
 'Crime, Drama',
 'Animation, Adventure, Comedy',
 'Action, Drama, History',
 'Action, Comedy, Thriller',
 'Drama, Fantasy, Horror',
 'Adventure, Drama, Fantasy',
 'Drama, Romance',
 'Drama',
 'Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Biography, Drama, History',
 'Action, Drama, War',
 'Crime, Drama',
 'Biography, Comedy, Drama',
 'Action, Drama, Mystery',
 'Action, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Drama',
 'Action, Drama, Fantasy',
 'Comedy, Drama, Romance',
 'Action, Adventure, Crime',
 'Biography, Drama, Romance',
 'Animation, Drama, Family',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Action, Adventure',
 'Comedy, Drama',
 'Action, Drama, History',
 'Comedy, Drama']

In [103]:
title = soup.find_all('h3', {'class':"lister-item-header"})
title

[<h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">1.</span>
 <a href="/title/tt15591076/">That '90s Show</a>
 <span class="lister-item-year text-muted unbold">(2023– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">2.</span>
 <a href="/title/tt13443470/">Wednesday</a>
 <span class="lister-item-year text-muted unbold">(2022– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">3.</span>
 <a href="/title/tt14826022/">You People</a>
 <span class="lister-item-year text-muted unbold">(2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">4.</span>
 <a href="/title/tt10813940/">Ginny &amp; Georgia</a>
 <span class="lister-item-year text-muted unbold">(2021– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">5.</span>
 <a href="/title/tt1520211/">The Walking Dead</a>
 <span class="lister-item-year text-muted unbold">(2010–2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">6.</span>
 <a href="/title/tt14138650/">The Pale Blue Eye</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">7.</span>
 <a href="/title/tt0165598/">That '70s Show</a>
 <span class="lister-item-year text-muted unbold">(1998–2006)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">8.</span>
 <a href="/title/tt11564570/">Glass Onion</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">9.</span>
 <a href="/title/tt1016150/">All Quiet on the Western Front</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">10.</span>
 <a href="/title/tt4565380/">Fauda</a>
 <span class="lister-item-year text-muted unbold">(2015– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">11.</span>
 <a href="/title/tt0903747/">Breaking Bad</a>
 <span class="lister-item-year text-muted unbold">(2008–2013)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">12.</span>
 <a href="/title/tt11311302/">Vikings: Valhalla</a>
 <span class="lister-item-year text-muted unbold">(2022– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">13.</span>
 <a href="/title/tt3428912/">Happy Valley</a>
 <span class="lister-item-year text-muted unbold">(2014–2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">14.</span>
 <a href="/title/tt15438246/">Kaleidoscope</a>
 <span class="lister-item-year text-muted unbold">(2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">15.</span>
 <a href="/title/tt9737876/">Narvik: Hitler's First Defeat</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">16.</span>
 <a href="/title/tt14579330/">Women at War</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">17.</span>
 <a href="/title/tt22352848/">Jung_E</a>
 <span class="lister-item-year text-muted unbold">(2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">18.</span>
 <a href="/title/tt7221388/">Cobra Kai</a>
 <span class="lister-item-year text-muted unbold">(2018–2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">19.</span>
 <a href="/title/tt3032476/">Better Call Saul</a>
 <span class="lister-item-year text-muted unbold">(2015–2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">20.</span>
 <a href="/title/tt2861424/">Rick and Morty</a>
 <span class="lister-item-year text-muted unbold">(2013– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">21.</span>
 <a href="/title/tt13131232/">Mission Majnu</a>
 <span class="lister-item-year text-muted unbold">(2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">22.</span>
 <a href="/title/tt12593682/">Bullet Train</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">23.</span>
 <a href="/title/tt4574334/">Stranger Things</a>
 <span class="lister-item-year text-muted unbold">(2016–2024)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">24.</span>
 <a href="/title/tt16913068/">Shahmaran</a>
 <span class="lister-item-year text-muted unbold">(2023– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">25.</span>
 <a href="/title/tt0413573/">Grey's Anatomy</a>
 <span class="lister-item-year text-muted unbold">(2005– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">26.</span>
 <a href="/title/tt7817340/">New Amsterdam</a>
 <span class="lister-item-year text-muted unbold">(2018–2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">27.</span>
 <a href="/title/tt2306299/">Vikings</a>
 <span class="lister-item-year text-muted unbold">(2013–2020)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">28.</span>
 <a href="/title/tt0460681/">Supernatural</a>
 <span class="lister-item-year text-muted unbold">(2005–2020)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">29.</span>
 <a href="/title/tt0364845/">NCIS</a>
 <span class="lister-item-year text-muted unbold">(2003– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">30.</span>
 <a href="/title/tt4786824/">The Crown</a>
 <span class="lister-item-year text-muted unbold">(2016–2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">31.</span>
 <a href="/title/tt7693316/">Devotion</a>
 <span class="lister-item-year text-muted unbold">(II) (2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">32.</span>
 <a href="/title/tt2442560/">Peaky Blinders</a>
 <span class="lister-item-year text-muted unbold">(2013–2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">33.</span>
 <a href="/title/tt14308636/">Bank of Dave</a>
 <span class="lister-item-year text-muted unbold">(2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">34.</span>
 <a href="/title/tt10795658/">Alice in Borderland</a>
 <span class="lister-item-year text-muted unbold">(2020– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">35.</span>
 <a href="/title/tt0092099/">Top Gun</a>
 <span class="lister-item-year text-muted unbold">(1986)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">36.</span>
 <a href="/title/tt0108778/">Friends</a>
 <span class="lister-item-year text-muted unbold">(1994–2004)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">37.</span>
 <a href="/title/tt13802576/">Lockwood &amp; Co</a>
 <span class="lister-item-year text-muted unbold">(2023– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">38.</span>
 <a href="/title/tt8178634/">RRR</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">39.</span>
 <a href="/title/tt1567432/">Teen Wolf</a>
 <span class="lister-item-year text-muted unbold">(2011–2017)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">40.</span>
 <a href="/title/tt1442437/">Modern Family</a>
 <span class="lister-item-year text-muted unbold">(2009–2020)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">41.</span>
 <a href="/title/tt16030542/">The Recruit</a>
 <span class="lister-item-year text-muted unbold">(2022– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">42.</span>
 <a href="/title/tt1655389/">Blonde</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">43.</span>
 <a href="/title/tt1488589/">Guillermo del Toro's Pinocchio</a>
 <span class="lister-item-year text-muted unbold">(2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">44.</span>
 <a href="/title/tt7335184/">You</a>
 <span class="lister-item-year text-muted unbold">(2018– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">45.</span>
 <a href="/title/tt2741602/">The Blacklist</a>
 <span class="lister-item-year text-muted unbold">(2013–2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">46.</span>
 <a href="/title/tt1844624/">American Horror Story</a>
 <span class="lister-item-year text-muted unbold">(2011– )</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">47.</span>
 <a href="/title/tt2560140/">Attack on Titan</a>
 <span class="lister-item-year text-muted unbold">(2013–2023)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">48.</span>
 <a href="/title/tt1632701/">Suits</a>
 <span class="lister-item-year text-muted unbold">(2011–2019)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">49.</span>
 <a href="/title/tt4179452/">The Last Kingdom</a>
 <span class="lister-item-year text-muted unbold">(2015–2022)</span>
 </h3>,
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">50.</span>
 <a href="/title/tt1586680/">Shameless</a>
 <span class="lister-item-year text-muted unbold">(2011–2021)</span>
 </h3>]

In [104]:
genres = soup.find_all('p', {'class':"genre"})
genres

[]

In [106]:
def scrape_imdb(n):
    title = []
    genre = []
    for i in range(1, n+1):
        url = f'https://www.imdb.com/search/title/?companies=co0144901&start={i}&ref_=adv_nxt'
        headers = {'Accept-Language': 'en-US,en;q=0.5'}
        
        response = requests.get(url, headers=headers)
        soup = bs(response.text, 'html.parser')

        # find all movie titles in the page
        titles = [a.text for a in soup.find_all('h3', {'class':"lister-item-header"})]
        
        # find genre 
       # genres = [a.text for a in soup.find_all('p', {'class':"genre"})]
        
        # find type

        # add the titles to the results list
        title += titles
        #genre += genres
        
    # create a DataFrame from the results
        df_imdb = pd.DataFrame({'title': titles})
    
    return df_imdb

# call the function to scrape 25000 results
df_imdb = scrape_imdb(10)

# display the first 5 results

In [107]:
df_imdb

                                              title
0                          \n10.\nFauda\n(2015– )\n
1                \n11.\nBreaking Bad\n(2008–2013)\n
2              \n12.\nVikings: Valhalla\n(2022– )\n
3                \n13.\nHappy Valley\n(2014–2023)\n
4                     \n14.\nKaleidoscope\n(2023)\n
5    \n15.\nNarvik: Hitler's First Defeat\n(2022)\n
6                     \n16.\nWomen at War\n(2022)\n
7                           \n17.\nJung_E\n(2023)\n
8                   \n18.\nCobra Kai\n(2018–2023)\n
9            \n19.\nBetter Call Saul\n(2015–2022)\n
10                \n20.\nRick and Morty\n(2013– )\n
11                   \n21.\nMission Majnu\n(2023)\n
12                    \n22.\nBullet Train\n(2022)\n
13            \n23.\nStranger Things\n(2016–2024)\n
14                     \n24.\nShahmaran\n(2023– )\n
15                \n25.\nGrey's Anatomy\n(2005– )\n
16              \n26.\nNew Amsterdam\n(2018–2023)\n
17                    \n27.\nVikings\n(2013–2020)\n
18               \n28.\nSupernatural\n(2005–2020)\n
19                          \n29.\nNCIS\n(2003– )\n
20                  \n30.\nThe Crown\n(2016–2023)\n
21                   \n31.\nDevotion\n(II) (2022)\n
22             \n32.\nPeaky Blinders\n(2013–2022)\n
23                    \n33.\nBank of Dave\n(2023)\n
24           \n34.\nAlice in Borderland\n(2020– )\n
25                         \n35.\nTop Gun\n(1986)\n
26                    \n36.\nFriends\n(1994–2004)\n
27                 \n37.\nLockwood & Co\n(2023– )\n
28                             \n38.\nRRR\n(2022)\n
29                  \n39.\nTeen Wolf\n(2011–2017)\n
30              \n40.\nModern Family\n(2009–2020)\n
31                   \n41.\nThe Recruit\n(2022– )\n
32                          \n42.\nBlonde\n(2022)\n
33  \n43.\nGuillermo del Toro's Pinocchio\n(2022)\n
34                           \n44.\nYou\n(2018– )\n
35              \n45.\nThe Blacklist\n(2013–2023)\n
36         \n46.\nAmerican Horror Story\n(2011– )\n
37            \n47.\nAttack on Titan\n(2013–2023)\n
38                      \n48.\nSuits\n(2011–2019)\n
39           \n49.\nThe Last Kingdom\n(2015–2022)\n
40                  \n50.\nShameless\n(2011–2021)\n
41                   \n51.\nSeinfeld\n(1989–1998)\n
42                   \n52.\nThe Witcher\n(2019– )\n
43                \n53.\nEmily in Paris\n(2020– )\n
44               \n54.\nBlack Mirror\n(2011–2019)\n
45               \n55.\nThe Good Doctor\n(2017– )\n
46                     \n56.\nOutlander\n(2014– )\n
47                         \n57.\nTreason\n(2022)\n
48                            \n58.\n1899\n(2022)\n
49                 \n59.\nWhite Noise\n(I) (2022)\n

In [108]:
df_imdb.describe()

                           title
count                         50
unique                        50
top     \n10.\nFauda\n(2015– )\n
freq                           1

In [109]:

df_imdb["Title_imdb"] = df_imdb["title"].str.extract(r'\n\d+\..*\n([^\n\(\)]+)\n')

In [81]:
df_imdb.sample(50)

,title,Title_imdb
91,\n43.\nGuillermo del Toro's Pinocchio\n(2022)\n,Guillermo del Toro's Pinocchio
317,\n24.\nShahmaran\n(2023– )\n,Shahmaran
148,\n51.\nSeinfeld\n(1989–1998)\n,Seinfeld
196,\n50.\nShameless\n(2011–2021)\n,Shameless
386,\n44.\nYou\n(2018– )\n,You
249,\n54.\nBlack Mirror\n(2011–2019)\n,Black Mirror
258,\n14.\nKaleidoscope\n(2023)\n,Kaleidoscope
65,\n17.\nJung_E\n(2023)\n,Jung_E
409,\n18.\nCobra Kai\n(2018–2023)\n,Cobra Kai
187,\n41.\nThe Recruit\n(2022– )\n,The Recruit
431,\n40.\nModern Family\n(2009–2020)\n,Modern Family
405,\n14.\nKaleidoscope\n(2023)\n,Kaleidoscope
228,\n33.\nBank of Dave\n(2023)\n,Bank of Dave
241,\n46.\nAmerican Horror Story\n(2011– )\n,American Horror Story
161,\n15.\nNarvik: Hitler's First Defeat\n(2022)\n,Narvik: Hitler's First Defeat
14,\n15.\nNarvik: Hitler's First Defeat\n(2022)\n,Narvik: Hitler's First Defeat
406,\n15.\nNarvik: Hitler's First Defeat\n(2022)\n,Narvik: Hitler's First Defeat
485,\n45.\nThe Blacklist\n(2013–2023)\n,The Blacklist
384,\n42.\nBlonde\n(2022)\n,Blonde
124,\n27.\nVikings\n(2013–2020)\n,Vikings
166,\n20.\nRick and Morty\n(2013– )\n,Rick and Morty
366,\n24.\nShahmaran\n(2023– )\n,Shahmaran
450,\n10.\nFauda\n(2015– )\n,Fauda
224,\n29.\nNCIS\n(2003– )\n,NCIS
260,\n16.\nWomen at War\n(2022)\n,Women at War
212,\n17.\nJung_E\n(2023)\n,Jung_E
273,\n29.\nNCIS\n(2003– )\n,NCIS
347,\n54.\nBlack Mirror\n(2011–2019)\n,Black Mirror
346,\n53.\nEmily in Paris\n(2020– )\n,Emily in Paris
150,\n4.\nGinny & Georgia\n(2021– )\n,Ginny & Georgia
379,\n37.\nLockwood & Co\n(2023– )\n,Lockwood & Co
312,\n19.\nBetter Call Saul\n(2015–2022)\n,Better Call Saul
444,\n53.\nEmily in Paris\n(2020– )\n,Emily in Paris
362,\n20.\nRick and Morty\n(2013– )\n,Rick and Morty
499,\n59.\nWhite Noise\n(I) (2022)\n,White Noise
265,\n21.\nMission Majnu\n(2023)\n,Mission Majnu
216,\n21.\nMission Majnu\n(2023)\n,Mission Majnu
5,\n6.\nThe Pale Blue Eye\n(2022)\n,The Pale Blue Eye
104,\n7.\nThat '70s Show\n(1998–2006)\n,That '70s Show
356,\n14.\nKaleidoscope\n(2023)\n,Kaleidoscope
137,\n40.\nModern Family\n(2009–2020)\n,Modern Family
43,\n44.\nYou\n(2018– )\n,You
199,\n53.\nEmily in Paris\n(2020– )\n,Emily in Paris
429,\n38.\nRRR\n(2022)\n,RRR
121,\n24.\nShahmaran\n(2023– )\n,Shahmaran
239,\n44.\nYou\n(2018– )\n,You
114,\n17.\nJung_E\n(2023)\n,Jung_E
480,\n40.\nModern Family\n(2009–2020)\n,Modern Family
204,\n9.\nAll Quiet on the Western Front\n(2022)\n,All Quiet on the Western Front
64,\n16.\nWomen at War\n(2022)\n,Women at War

### CSV File - My Netflix viewing list

In [117]:
with open("data/netflix_viewing-history.csv") as f:
    print(f)

<_io.TextIOWrapper name='data/netflix_viewing-history.csv' mode='r' encoding='cp1252'>

In [69]:
df_net = pd.read_csv("data/netflix_viewing-history.csv")

In [70]:
df_net.describe()

               Title        Date
count           6177        6177
unique          5857        1177
top      : Episode 1  27/11/2022
freq               7          45

In [71]:
df_net.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6177 entries, 0 to 6176
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   6177 non-null   object
 1   Date    6177 non-null   object
dtypes: object(2)
memory usage: 96.6+ KB

In [72]:
df_net

                                      Title        Date
0                             The Godfather  29/01/2023
1                                    Trolls  29/01/2023
2         VINLAND SAGA: Season 1: Episode 1  29/01/2023
3     Arrested Development: Season 1: Pilot  29/01/2023
4                             Puss in Boots  29/01/2023
...                                     ...         ...
6172                                   Room  01/04/2019
6173                             Safe House  17/12/2018
6174                             Win It All  16/12/2018
6175                            The Cobbler  16/12/2018
6176             The Fundamentals of Caring  13/12/2018

[6177 rows x 2 columns]

In [73]:
df_net["Title_net"] = df_net["Title"].str.extract(r"^([^:]+)")

In [74]:
df_net.sample(5)

,Title,Date,Title_net
372,High Score: Limited Series: Comeback Kid,03/09/2020,High Score
643,The Stranger: Limited Series: Episode 1,10/03/2020,The Stranger
5425,Workin' Moms: Season 3: Stand for Something,09/09/2019,Workin' Moms
3487,Despicable Me 3,13/03/2021,Despicable Me 3
3657,Friends: Season 8: The One with Rachel's Date,14/02/2021,Friends

### Merge IMDB and Netflix Lists

In [59]:
def merge_dfs(df_imdb, df_net, on='Title2'):
    if on in df_imdb.columns and on in df_net.columns:
        df_net = df_net.rename(columns={ on:f'{on}_right'})
        #on = f'{on}_right'
    df_merged = pd.merge(df_imdb, df_net, on=on)
    return df_merged

In [67]:
df_net.describe()

               Title        Date     Title2
count           6177        6177       6177
unique          5857        1177        832
top      : Episode 1  27/11/2022  Star Trek
freq               7          45        488

In [68]:
df_imdb.describe()

                                  title     Title2
count                               500        500
unique                               59         59
top     \n30.\nThe Crown\n(2016–2023)\n  The Crown
freq                                 10         10

In [82]:
merge_dfs = pd.merge(df_net, df_imdb, left_on='Title_net', right_on='Title_imdb', how='left')

In [83]:
merge_dfs.describe()

,Title,Date,Title_net,title,Title_imdb
count,13986,13986,13986,8726,8726
unique,5857,1177,832,27,27
top,Stranger Things: Stranger Things 2: Chapter Si...,01/02/2021,Modern Family,\n40.\nModern Family\n(2009–2020)\n,Modern Family
freq,20,206,2490,2490,2490

In [86]:
df_imdb['Title_imdb'].unique

<bound method Series.unique of 0        That '90s Show
1             Wednesday
2            You People
3       Ginny & Georgia
4      The Walking Dead
             ...
495     The Good Doctor
496           Outlander
497             Treason
498                1899
499         White Noise
Name: Title_imdb, Length: 500, dtype: object>

In [88]:
df_net['Title_net'].unique

<bound method Series.unique of 0                    The Godfather
1                           Trolls
2                     VINLAND SAGA
3             Arrested Development
4                    Puss in Boots
                   ...
6172                          Room
6173                    Safe House
6174                    Win It All
6175                   The Cobbler
6176    The Fundamentals of Caring
Name: Title_net, Length: 6177, dtype: object>

In [89]:
merge_dfs.sample(20)

,Title,Date,Title_net,title,Title_imdb
570,Good Girls: Season 3: Au Jus,29/07/2020,Good Girls,NaN,NaN
4046,Star Trek: Enterprise: Season 1: Strange New W...,11/06/2021,Star Trek,NaN,NaN
4218,Seinfeld: Season 6: The Secretary,11/03/2021,Seinfeld,\n51.\nSeinfeld\n(1989–1998)\n,Seinfeld
1119,The Walking Dead: Season 6: Last Day on Earth,07/04/2018,The Walking Dead,\n5.\nThe Walking Dead\n(2010–2022)\n,The Walking Dead
7505,Modern Family: Season 11: Pool Party,22/02/2021,Modern Family,\n40.\nModern Family\n(2009–2020)\n,Modern Family
6154,Modern Family: Season 4: Flip Flop,18/05/2021,Modern Family,\n40.\nModern Family\n(2009–2020)\n,Modern Family
10012,Modern Family: Season 8: Grab It!,28/12/2020,Modern Family,\n40.\nModern Family\n(2009–2020)\n,Modern Family
11356,Modern Family: Season 10: Stand By Your Man,18/06/2020,Modern Family,\n40.\nModern Family\n(2009–2020)\n,Modern Family
9348,Friends: Season 3: The One with the Flashback,27/01/2021,Friends,\n36.\nFriends\n(1994–2004)\n,Friends
13681,Peaky Blinders: Season 2: Episode 1,23/02/2019,Peaky Blinders,\n32.\nPeaky Blinders\n(2013–2022)\n,Peaky Blinders
10822,Cobra Kai: Season 2: Glory of Love,09/01/2020,Cobra Kai,\n18.\nCobra Kai\n(2018–2023)\n,Cobra Kai
9957,Modern Family: Season 8: Do You Believe in Magic?,29/12/2020,Modern Family,\n40.\nModern Family\n(2009–2020)\n,Modern Family
3916,Seinfeld: Season 7: The Wig Master,11/10/2021,Seinfeld,\n51.\nSeinfeld\n(1989–1998)\n,Seinfeld
2877,Star Trek: The Next Generation: Season 1: Haven,17/05/2022,Star Trek,NaN,NaN
1944,Manifest: Season 4: Go-Around,15/11/2022,Manifest,NaN,NaN
4913,You: Season 3: We're All Mad Here,17/10/2021,You,\n44.\nYou\n(2018– )\n,You
13826,Better Call Saul: Season 4: Wiedersehen,21/01/2019,Better Call Saul,\n19.\nBetter Call Saul\n(2015–2022)\n,Better Call Saul
2931,Better Call Saul: : Episode 1,05/06/2022,Better Call Saul,\n19.\nBetter Call Saul\n(2015–2022)\n,Better Call Saul
8327,Friends: Season 7: The One with Ross' Library ...,02/11/2021,Friends,\n36.\nFriends\n(1994–2004)\n,Friends
5376,Archer: Season 5: Archer Vice: House Call,09/10/2021,Archer,NaN,NaN